name: Sync with Codeberg

on:
  schedule:
    - cron: '0 0 */3 * *'  # Run every 3 days at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: 'master'

    - name: Add Codeberg remote
      run: |
        rm -rf *
        git clone --depth=1 --branch=clang https://codeberg.org/emmett1/alicelinux.git

    - name: Merge changes from Codeberg
      run: |
        git config user.name '󰬭 [CI] '
        git config user.email 'action@github.com'

        rm -rf LICENSE README.md .woodpecker.yml
        mv ./alicelinux/repos/clang/* .
        rm -rf ./alicelinux
        git add .
        git commit -s -m "sync"

    - name: Push changes to GitHub
      run: |
        git push origin master
