name: Sync with Codeberg

on:
  schedule:
    - cron: '0 0 */3 * *'  # Run every 3 days at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: 'master'

    - name: Add Codeberg remote
      run: |
        git remote add codeberg https://codeberg.org/emmett1/alicelinux.git
        git fetch codeberg

    - name: Merge changes from Codeberg
      run: |
        git config user.name '󰬭 [CI] '
        git config user.email 'action@github.com'

        git checkout --orphan temp-branch
        git rm -rf LICENSE README.md .woodpecker.yml .
        git checkout codeberg/clang -- repos/clang
        git mv repos/clang/* .
        git rm -r repos
        git commit -m "Import changes from Codeberg"

        git checkout master
        git merge temp-branch --allow-unrelated-histories
        git branch -D temp-branch

    - name: Push changes to GitHub
      run: |
        git push origin master
